package entities;
// Generated 2019-04-28 23:44:05 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private int id;
     private Orders orders;
     private String type;
     private String name;
     private BigDecimal price;

    public Products() {
    }

    public Products(int id, Orders orders, String type, String name, BigDecimal price) {
       this.id = id;
       this.orders = orders;
       this.type = type;
       this.name = name;
       this.price = price;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public Orders getOrders() {
        return this.orders;
    }
    
    public void setOrders(Orders orders) {
        this.orders = orders;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    @Override
    public String toString(){
        return String.format("Product | Id: %d, Order id: %d, Type: %s, Name: %s, Price: %f", id, orders.getId(), type, name, price);
    }


}


