package entities;
// Generated 2019-05-11 16:25:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;

/**
 * Orders generated by hbm2java
 */
public class Orders  implements java.io.Serializable {


     private BigDecimal id;
     private Date creationdate;
     private String clientfirstname;
     private String clientlastname;
     private Date deliverydate;
     private String deliverymethod;
     private String deliveryaddress;

    public Orders() {
    }

    public Orders(BigDecimal id, Date creationdate, String clientfirstname, String clientlastname, Date deliverydate, String deliverymethod, String deliveryaddress) {
       this.id = id;
       this.creationdate = creationdate;
       this.clientfirstname = clientfirstname;
       this.clientlastname = clientlastname;
       this.deliverydate = deliverydate;
       this.deliverymethod = deliverymethod;
       this.deliveryaddress = deliveryaddress;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public Date getCreationdate() {
        return this.creationdate;
    }
    
    public void setCreationdate(Date creationdate) {
        this.creationdate = creationdate;
    }
    public String getClientfirstname() {
        return this.clientfirstname;
    }
    
    public void setClientfirstname(String clientfirstname) {
        this.clientfirstname = clientfirstname;
    }
    public String getClientlastname() {
        return this.clientlastname;
    }
    
    public void setClientlastname(String clientlastname) {
        this.clientlastname = clientlastname;
    }
    public Date getDeliverydate() {
        return this.deliverydate;
    }
    
    public void setDeliverydate(Date deliverydate) {
        this.deliverydate = deliverydate;
    }
    public String getDeliverymethod() {
        return this.deliverymethod;
    }
    
    public void setDeliverymethod(String deliverymethod) {
        this.deliverymethod = deliverymethod;
    }
    public String getDeliveryaddress() {
        return this.deliveryaddress;
    }
    
    public void setDeliveryaddress(String deliveryaddress) {
        this.deliveryaddress = deliveryaddress;
    }




}


