package entities;
// Generated 2019-05-11 16:25:49 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * Products generated by hbm2java
 */
public class Products  implements java.io.Serializable {


     private BigDecimal id;
     private String type;
     private String name;
     private BigDecimal price;
     private BigDecimal orderid;

    public Products() {
    }

    public Products(BigDecimal id, String type, String name, BigDecimal price, BigDecimal orderid) {
       this.id = id;
       this.type = type;
       this.name = name;
       this.price = price;
       this.orderid = orderid;
    }
   
    public BigDecimal getId() {
        return this.id;
    }
    
    public void setId(BigDecimal id) {
        this.id = id;
    }
    public String getType() {
        return this.type;
    }
    
    public void setType(String type) {
        this.type = type;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public BigDecimal getPrice() {
        return this.price;
    }
    
    public void setPrice(BigDecimal price) {
        this.price = price;
    }
    public BigDecimal getOrderid() {
        return this.orderid;
    }
    
    public void setOrderid(BigDecimal orderid) {
        this.orderid = orderid;
    }




}


